name: CMake

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.19.2' # Use the appropriate version of CMake

    - name: Configure
      run: cmake -S ./sun-sensor-simulator/ -B ./sun-sensor-simulator/build

    - name: Build
      run: cmake --build ./sun-sensor-simulator/build

    - name: Run tests
      run: cd ./sun-sensor-simulator/build/
      run: ctest ./all_tests 

